#
#    Makefile for libncipher
#

install-doc: LICENSE ncps-001.md ncps-002.md ncps-003.md
	install -pd $(DOCDIR)/ncp_spec
	install -pm 644 LICENSE $(DOCDIR)/ncp_spec
	install -pm 644 *.md $(DOCDIR)/ncp_spec
